DROP TABLE IF EXISTS VENTE;
DROP TABLE IF EXISTS APPARTEMENT;
DROP TABLE IF EXISTS IMMEUBLE;
DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
    IdClient SERIAL PRIMARY KEY,
    Nom TEXT,
    Telephone TEXT
);

CREATE TABLE IMMEUBLE (
    IdImmeuble SERIAL PRIMARY KEY,
    Adresse TEXT,
    Ville TEXT
);

CREATE TABLE APPARTEMENT (
    IdAppartement SERIAL PRIMARY KEY,
    NumAppartement INT,
    Surface FLOAT,
    Prix FLOAT,
    IdImmeuble INT REFERENCES IMMEUBLE(IdImmeuble)
);

CREATE TABLE VENTE (
    IdVente SERIAL PRIMARY KEY,
    DateVente DATE,
    IdClient INT REFERENCES CLIENT(IdClient),
    IdAppartement INT REFERENCES APPARTEMENT(IdAppartement)
);

INSERT INTO CLIENT (Nom, Telephone) VALUES
('Alice', '111111'),
('Bob', '222222');